server {
    listen 80;
    server_name localhost;
    root /var/www/html/web; # Pointing to the 'web' folder of Yii2
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000; # 'app' is the name of your php service
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
